""" given a list of numbers, make a list of full file names for all the trees needed, to be used as input to rsync.
The numbers are generated by an sqlite query on summary and wikidays, which is generated by wiki_day_db.py
"""
import MDSplus as MDS
import numpy as np
import sys

if len(sys.argv)>1:
    shots = eval(sys.argv[1])
else:
    shots = np.loadtxt('/data/datamining/MHD_shots_2009_2017.txt', dtype=int)

need = []
for (i,shot) in enumerate(shots):
    if i%100 == 0: print(shot)
    trees = 'h1data,mirnov,electr_dens,fluctuations'.split(',')
    trees.remove('fluctuations')  # this causes unnecessary copies as I often don't copy flucs
    if shot < 72144:
        trees.remove('mirnov')
    try:
        for tree in trees:
            tr = MDS.Tree(tree, shot)
    except:
        need.append(shot)

print(len(need), 'shots')        

lst = open('/tmp/shotlist.txt','w')        
for shot in need:
    trees = 'h1data,mirnov,electr_dens,fluctuations'.split(',')
    if shot < 72144:
        trees.remove('mirnov')

    if shot > 94000:
        path='h1/recent/'
    else:
        path = str('h1/sorted/{top4:04d}/'.format(top4=shot//100))

    for tr in trees:
        for typ in 'characteristics,datafile,tree'.split(','):
            lst.write('{path}{tr}_{shot}.{typ}\n'.format(path=path,tr=tr,shot=shot,typ=typ))
lst.close()
